src/main/java/stackjava/com/springmvchibernate/entities/Product.java
package stackjava.com.springmvchibernate.entities;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.Lob;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

@Entity
@Table(name = "product")
public class Product {
	@Id
	@Column(name = "productid")
	private int productid;

	@ManyToOne
	@JoinColumn(name = "productma")
	private Category category;
	
	
    @Lob
    @Column(name = "productimage")
    private byte[] productimage;

    @Column(name = "sanid")
	private int sanid;

    @Column(name = "productprice")
	private int productprice;

	@Column(name = "productdescription")
	private String productdescription;
	
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "ngaytao")
	private Date ngaytao;

	@Column(name = "nguoitao")
	private String nguoitao;
	
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "ngaysua")
	private Date ngaysua;

	@Column(name = "nguoisua")
	private String nguoisua;

    @Column(name = "daxoa")
	private int daxoa;
    
    @Column(name = "chaid")
	private int chaid;
	
	public Product() {
		
	}

	public int getChaid() {
		return chaid;
	}

	public void setChaid(int chaid) {
		this.chaid = chaid;
	}

	public int getProductid() {
		return productid;
	}

	public void setProductid(int productid) {
		this.productid = productid;
	}

	public Category getCategory() {
		return category;
	}

	public void setCategory(Category category) {
		this.category = category;
	}

	public byte[] getProductimage() {
		return productimage;
	}

	public void setProductimage(byte[] productimage) {
		this.productimage = productimage;
	}
	
	
	public int getSanid() {
		return sanid;
	}

	public void setSanid(int sanid) {
		this.sanid = sanid;
	}

	public int getProductprice() {
		return productprice;
	}

	public void setProductprice(int productprice) {
		this.productprice = productprice;
	}

	public String getProductdescription() {
		return productdescription;
	}

	public void setProductdescription(String productdescription) {
		this.productdescription = productdescription;
	}

	public Date getNgaytao() {
		return ngaytao;
	}

	public void setNgaytao(Date ngaytao) {
		this.ngaytao = ngaytao;
	}

	public String getNguoitao() {
		return nguoitao;
	}

	public void setNguoitao(String nguoitao) {
		this.nguoitao = nguoitao;
	}

	public Date getNgaysua() {
		return ngaysua;
	}

	public void setNgaysua(Date ngaysua) {
		this.ngaysua = ngaysua;
	}

	public String getNguoisua() {
		return nguoisua;
	}

	public void setNguoisua(String nguoisua) {
		this.nguoisua = nguoisua;
	}

	public int getDaxoa() {
		return daxoa;
	}

	public void setDaxoa(int daxoa) {
		this.daxoa = daxoa;
	}
    
}

src/main/java/stackjava/com/springmvchibernate/model/Cart.java
package stackjava.com.springmvchibernate.model;

import java.util.ArrayList;
import java.util.List;

public class Cart {
	private final List<Item> cartLines = new ArrayList<Item>();

    public List<Item> getCartLines() {
        return this.cartLines;
    }

    private Item findLineByCode(String code) {
        for (Item line : this.cartLines) {
            if (line.getProduct().getProductId() == Integer.parseInt(code)) {
                return line;
            }
        }
        return null;
    }
 
    public void addProduct(ProductInfo p, int quantity) {
    	Item line = this.findLineByCode(String.valueOf(p.getProductId()));
 
        if (line == null) {
            line = new Item();
            line.setQuantity(0);
            line.setProduct(p);
            this.cartLines.add(line);
        }
        int newQuantity = line.getQuantity() + quantity;
        if (newQuantity <= 0) {
            this.cartLines.remove(line);
        } else {
            line.setQuantity(newQuantity);
        }
    }
 
    public void validate() {
 
    }
 
    public void updateProduct(String code, int quantity) {
    	Item line = this.findLineByCode(code);
 
        if (line != null) {
            if (quantity <= 0) {
                this.cartLines.remove(line);
            } else {
                line.setQuantity(quantity);
            }
        }
    }
 
    public void removeProduct(ProductInfo p) {
    	Item line = this.findLineByCode(String.valueOf(p.getProductId()));
        if (line != null) {
            this.cartLines.remove(line);
        }
    }
 
    public int getQuantityTotal() {
        int quantity = 0;
        for (Item line : this.cartLines) {
            quantity += line.getQuantity();
        }
        return quantity;
    }
 
    public double getAmountTotal() {
        double total = 0;
        for (Item line : this.cartLines) {
            total += line.getAmount();
        }
        return total;
    }
 
    public void updateQuantity(Cart c) {
        if (c != null) {
            List<Item> lines = c.getCartLines();
            for (Item line : lines) {
                this.updateProduct(String.valueOf(line.getProduct().getProductId()), line.getQuantity());
            }
        }
 
    }
}

src/main/webapp/WEB-INF/views/jsp/checkout.jsp
<!DOCTYPE html>
<html>
<head>
<title>Shop Hoàng Anh Sport</title>
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form"%>
<c:set var="root" value="${pageContext.request.contextPath}"/>

<link rel="stylesheet" type="text/css" href="${root}/css/bootstrap.css">

<script src="${root}/js/jquery.min.js"></script>

<link rel="stylesheet" type="text/css" href="${root}/css/style.css">

<script>
    function getHuyen() {
    $.ajax({
        async: false,
        url: "fetchDonViHanhChinh",
        type: "POST",
        dataType: "json",
        data: {            
            'isAction': "getHuyenTP",
            'tinhTPId': $("#diaChiTinhId").val()           
        },      
        success: function(results) {        	
            var htmlCombo = "<option value='0'>Ch&#7885;n Qu&#7853;n/Huy&#7879;n</option>";
            var htmlCombo1 = "<option value='0'>Ch&#7885;n x&atilde;</option>";
            $.each(results, function(key, value) {
            	if(value.key!="value") {
                	htmlCombo += "<option value='" + value.id + "'>"+ value.name + "</option>";
            	}
            });
            $('#diaChiHuyenId').html(htmlCombo);
            $('#diaChiXaId').html(htmlCombo1); 
        },
        error: function () {
            console.log("Error");
        }
    });
}    
function getXa() {
    $.ajax({
        async: false,
        url: "fetchDonViHanhChinh",
        type: "POST",
        dataType: "json",
        data: {            
            'isAction': "getXaTP",
            'tinhTPId': $("#diaChiHuyenId").val()           
        },      
        success: function(results) {        	
            var htmlCombo = "<option value='0'>Ch&#7885;n x&atilde;</option>";
            $.each(results, function(key, value) {
            	if(value.key!="value") {
                	htmlCombo += "<option value='" + value.id + "'>"+ value.name + "</option>";
            	}
            });
            $('#diaChiXaId').html(htmlCombo);     
        },
        error: function () {
            console.log("Error");
        }
    });
}     
</script>
</head>
<body>
	
	<jsp:include page="header.jsp"></jsp:include>
	
	<div class="container">
		<div class="account">
			<h2 class="account-in">Thông tin</h2>
			<form:form 
				action="${root}/${action}" 
				modelAttribute="info_customer" 
				method="POST" 
				autocomplete="off" >
				<div>
					<span style="padding-right: 2em;">Họ và tên<b style="color: red;"> *</b></span> 
					<form:input type="text" id="customername" path="customername" autocomplete="off" required="required" />
				</div>
				<div>
					<span style="padding-right: 1.85em;">Điện thoại<b style="color: red;"> *</b></span> 
					<form:input type="text" id="customerphone" path="customerphone" autocomplete="off" required="required" />
				</div>
				<div>
					<span style="padding-right: 3.4em;">Địa chỉ<b style="color: red;"> *</b></span> 
					<form:input type="text" id="customeraddress" path="customeraddress" autocomplete="off" required="required" />
				</div>
				<div class="row mb40" style="margin-left: 115px;">
					<div class="col-md-4" style="width: 22.5%;">
						<form:select class="form-control" style="width: 90%;"
							path="diaChiTinhId" id="diaChiTinhId" onChange="getHuyen()">
							<form:option value="0">--Chọn Tỉnh/TP--</form:option>
							<c:forEach items="${cateListDVHC}" var="c">
								<form:option value="${c.id}">${c.ten}</form:option>
							</c:forEach>
						</form:select>
					</div>
					<div class="col-md-4" style="width: 22.5%;">
						<form:select class="form-control" style="width: 90%;" id="diaChiHuyenId" path="diaChiHuyenId" onChange="getXa()">
							<form:option value="0">--Chọn quận/ huyện--</form:option>
						</form:select>
					</div>
					<div class="col-md-4" style="width: 22.5%;">
						<form:select class="form-control" style="width: 90%;" id="diaChiXaId" path="diaChiXaId">
							<form:option value="0">--Chọn xã/ phường--</form:option>
						</form:select>
					</div>
				</div>
				<input type="submit" value="Thanh toán">
			</form:form>
		</div>
	</div>

	<jsp:include page="footer.jsp"></jsp:include>

</body>
</html>

src/main/webapp/WEB-INF/views/jsp/container.jsp
<%@page contentType="text/html" pageEncoding="UTF-8"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<c:set var="root" value="${pageContext.request.contextPath}" />
<div class="container">
	<div class="content">
		<div class="content-middle">
			<h3 class="future">Logo Đội</h3>
			<div class="content-middle-in">
				<ul id="flexiselDemo1">		
					<c:if test="${not empty cateList_Product}">
						<c:forEach var="c" items="${cateList_Product}" varStatus="itr">	
							<li><img src="${root}/productImageLogo?id=${c.categoryid}"></li>
						</c:forEach>
					</c:if>	
				</ul>
				<script type="text/javascript">
					$(window).load(function() {
						$("#flexiselDemo1").flexisel({
							visibleItems : 4,
							animationSpeed : 1000,
							autoPlay : true,
							autoPlaySpeed : 3000,
							pauseOnHover : true,
							enableResponsiveBreakpoints : true,
							responsiveBreakpoints : {
								portrait : {
									changePoint : 480,
									visibleItems : 1
								},
								landscape : {
									changePoint : 640,
									visibleItems : 2
								},
								tablet : {
									changePoint : 768,
									visibleItems : 3
								}
							}
						});

					});
				</script>
				<script type="text/javascript" src="${root}/js/jquery.flexisel.js"></script>
			</div>
		</div>
			
	</div>
</div>

src/main/webapp/WEB-INF/views/jsp/footer.jsp
<%@page contentType="text/html" pageEncoding="UTF-8"%>
<div class="footer">
		<p class="footer-class">
			&copy; 2018 Shop Hoàng Anh Sport template | design <a href="#">Hoàng Anh</a> | Email <a href="#" target="_blank">crhoang7@gmail.com</a><br>
	Địa Chỉ: k35/36 Tô Hiến Thành phường Phước Mỹ Quận Sơn Trà thành phố Đà Nẵng<br>
	Skype: <a href="#" target="_blank">conghoangnguyen2802</a> | Điện thoại liên hệ: <a href="#" target="_blank">01626045320</a>
		</p><!-- 
		<script type="text/javascript">
			$(document).ready(function() {				
				$().UItoTop({
					easingType : 'easeOutQuart'
				});

			});
		</script> -->
		<a href="#" id="toTop" style="display: block;"> <span
			id="toTopHover" style="opacity: 1;"> </span></a>
	</div>

src/main/webapp/WEB-INF/views/jsp/header.jsp
<%@page contentType="text/html" pageEncoding="UTF-8"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<c:set var="root" value="${pageContext.request.contextPath}"/>

<div class="header">
	<div class="header-bottom">
		<div class="container">
			<div class="h_menu4">
				<a class="toggleMenu" href="#">Menu</a>
				<ul class="nav">
					<li class="active"><a href="${root}/index"><i> </i>Trang chủ</a></li>
					<li><a href="#">Đồ bóng đá</a>
						<ul class="drop">
							<c:forEach items="${cateList}" var="c">
								<li>
									<a href="${root}/customerProduct/${c.categoryid}">${c.categoryname}</a>								
								</li>
							</c:forEach>							
						</ul></li>
					<li><a href="#"> ĐỒ BÓNG RỔ</a></li>
					<li><a href="#">THÔNG TIN</a></li>
					<li><a href="#">KHUYẾN MÃI</a></li>
					<li><a href="${root }/checkoutProductCart">THANH TOÁN</a></li>
					<li><a href="${root}/login">ĐĂNG NHẬP</a></li>
				</ul>
				<script type="text/javascript" src="${root}/js/nav.js"></script>
			</div>
		</div>
	</div>
	<div class="header-bottom-in">
		<div class="container">
			<div class="header-bottom-on">
				<p class="wel"><a href="#">Rất hân hạnh được phục vụ quý khách.</a></p>
				<div class="header-can">
					
					<div class="header-in">
						<ul class="icon1 sub-icon1">							
							<li><div class="cart">
									<a href="#" class="cart-in"> </a>
									<span> ${myCart.quantityTotal}</span>
								</div>
								<ul class="sub-icon1 list">
									<h3 style="text-align: center;">Đã chọn  sản phẩm</h3>
									<div class="shopping_cart">
										<c:forEach items="${cartForm.cartLines}" var="c"
               								varStatus="varStatus">								
												<div class="cart_box">
	                                               <div class="message">
	                                                 <div class="alert-close"><a href="#"></a></div>
	                                                   <div class="list_desc">
	                                                   	<h4><a href="#">${c.product.name} 
	                                                   		<c:if test="${c.product.sanid=='1'}">
																sân nhà
															</c:if>	
	                                                   		<c:if test="${c.product.sanid=='2'}">
																sân khách
															</c:if> </a></h4>
	                                                      ${c.quantity} x
	                                                       <span class="actual"> ${c.product.productPrice}.000</span>
	                                                   </div>
	                                                   <div class="clearfix"></div>
	                                               </div>
	                                           </div>
										</c:forEach>
									</div>
									<div class="total">
										<div class="total_left">Tổng tiền :</div>
										<div class="total_right">${myCart.amountTotal}00 vnđ</div>
										<div class="clearfix"></div>
									</div>
									<div class="login_buttons">
										<div class="check_button">			
											<a href="${root }/checkoutProductCart">Thanh Toán</a>
										</div>
										<div class="clearfix"></div>
									</div>
								</ul>
							</li>
						</ul>
					</div>
					<div class="clearfix"></div>
				</div>
				<div class="clearfix"></div>
			</div>
		</div>
	</div>
</div>

src/main/webapp/WEB-INF/views/jsp/index.jsp
<html>
<head>
<title>Shop Hoàng Anh Sport</title>
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<c:set var="root" value="${pageContext.request.contextPath}"/>
<link rel="stylesheet" type="text/css" href="${root}/css/bootstrap.css">
<script src="${root}/js/jquery.min.js"></script>
<link rel="stylesheet" type="text/css" href="${root}/css/style.css">

<script type="text/javascript" src="${root}/js/move-top.js"></script>
<script type="text/javascript" src="${root}/js/easing.js"></script>

<link rel="stylesheet" type="text/css" href="${root}/css/etalage.css">
<script src="${root}/js/jquery.etalage.min.js"></script>
		<script>
			jQuery(document).ready(function($){
				$('#etalage').etalage({
					thumb_image_width: 300,
					thumb_image_height: 400,
					source_image_width: 900,
					source_image_height: 1200,
					show_hint: true,
					click_callback: function(image_anchor, instance_id){
						alert('Callback example:\nYou clicked on an image with the anchor: "'+image_anchor+'"\n(in Etalage instance: "'+instance_id+'")');
					}
				});
			});
		</script>

<script src="${root}/js/responsiveslides.min.js"></script>
<script>
	$(function() {
		$("#slider1").responsiveSlides({
			auto : true,
			speed : 500,
			namespace : "callbacks",
			pager : true,
		});
	});
</script>

</head>
<body>
	<jsp:include page="header.jsp"></jsp:include>

	<c:if test="${empty listCustomerProduct && empty customerProductSingle}">
		<jsp:include page="slidershow.jsp"></jsp:include>
		<jsp:include page="container.jsp"></jsp:include>
	</c:if>
	
	<c:if test="${not empty listCustomerProduct && empty customerProductSingle}">
		<jsp:include page="product.jsp"></jsp:include>
	</c:if>
	
	<c:if test="${empty listCustomerProduct && not empty customerProductSingle}">
		<jsp:include page="single.jsp"></jsp:include>
	</c:if>
	
	<jsp:include page="footer.jsp"></jsp:include>
</body>
</html>

src/main/webapp/WEB-INF/views/jsp/login.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@page session="true"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<title>Login Page</title>
	<c:set var="root" value="${pageContext.request.contextPath}"/>
<script src="${root}/js/jquery.min.js"></script>
<script src="${root}/js/bootstrap.min.js"></script> 
<link rel="stylesheet" href="${root}/css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="${root}/css/stylelogin.css"/>
</head>
<body>
	<div class="login-form">		
		<form name='loginForm' action="<c:url value='/j_spring_security_check' />" method='POST'>			
			<h2 class="text-center">Log in</h2>
			<c:if test="${not empty error}">
				<div style="text-align: center;color: red;">${error}</div>
			</c:if>
			<c:if test="${not empty msg}">
				<div style="text-align: center;color: blue;">${msg}</div>
			</c:if>
			<div class="form-group">
            	<input type="text" class="form-control" name="username" >
        	</div>
        	<div class="form-group">
            	<input type="password" class="form-control" name="password" >
			</div>
			<div class="form-group">
            <button type="submit" class="btn btn-primary btn-block">Log in</button>
            </div>				
			<input type="hidden" name="${_csrf.parameterName}" value="${_csrf.token}" />
		</form>
		
	</div>
</body>
</html>

src/main/webapp/WEB-INF/views/jsp/product.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ taglib prefix="tag" uri="/WEB-INF/taglibs/customTaglib.tld" %>
<c:set var="root" value="${pageContext.request.contextPath}"/>
	<div class="container">
		<div class="content" style="padding: 4em 0 0 0;">
			<div class="content-middle">
				<h3 class="future">Logo Đội</h3>
				<div class="content-middle-in">
					<ul id="flexiselDemo1">
						<c:if test="${not empty cateList_Product}">
							<c:forEach var="c" items="${cateList_Product}" varStatus="itr">	
								<li><img src="${root}/productImageLogo?id=${c.categoryid}"></li>
							</c:forEach>
						</c:if>	
					</ul>
					<script type="text/javascript">
						$(window).load(function() {
							$("#flexiselDemo1").flexisel({
								visibleItems : 4,
								animationSpeed : 1000,
								autoPlay : true,
								autoPlaySpeed : 3000,
								pauseOnHover : true,
								enableResponsiveBreakpoints : true,
								responsiveBreakpoints : {
									portrait : {
										changePoint : 480,
										visibleItems : 1
									},
									landscape : {
										changePoint : 640,
										visibleItems : 2
									},
									tablet : {
										changePoint : 768,
										visibleItems : 3
									}
								}
							});

						});
					</script>
					<script type="text/javascript" src="${root}/js/jquery.flexisel.js"></script>
				</div>
			</div>
		</div>

		<div class="products">
		<h2 class=" products-in">Sản Phẩm</h2>
		<div class="top-products">
			<c:if test="${not empty listCustomerProduct}">
				<%int count = 0; int i = 4;%>
				<c:forEach var="c" items="${listCustomerProduct}" varStatus="itr">					
					<div class="col-md-3 md-col">
						<div class="col-md">
							<a href="${root}/customerProductSingle/${c.productid}/${id}" class="compare-in"> 
								<img src="${root}/productImage?id=${c.productid}">
								<div class="compare">
									<span>Chi Tiết</span>
								</div>
							</a>
							<div class="top-content">
								<h5 style="text-align: center;">
									<c:if test="${c.sanid == '1' }">
										<a href="#">${c.category.categoryname } sân nhà</a>
									</c:if>
									<c:if test="${c.sanid == '2' }">
										<a href="#">${c.category.categoryname } sân khách</a>
									</c:if>
								</h5>
								<div class="white">
									<a href="${root}/customerProductCart/${c.productid}/${id}"
										class="hvr-shutter-in-vertical hvr-shutter-in-vertical2">Thêm Giỏ Hàng</a>
									<p class="dollar">
										<span>${c.productprice}</span><span class="in-dollar">vnđ</span>
									</p>
									<div class="clearfix"></div>
								</div>
							</div>
						</div>
					</div>
					<%count++; if(count == i) {i=i+4;%>
			<div class="clearfix"></div>
		</div>
		<div class="top-products">
					<%} %>
				</c:forEach>
			</c:if>
			<div class="clearfix"></div>
		</div>
		<tag:paginate max="12" offset="${offset}" count="${count}" uri="${root}/customerProduct/${id}" next="&raquo;" previous="&laquo;"/>
	</div>
	</div>
	

src/main/webapp/WEB-INF/views/jsp/single.jsp
<%@page contentType="text/html" pageEncoding="UTF-8"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<c:set var="root" value="${pageContext.request.contextPath}"/>
<div class="container">
			<div class="single">
				<div class="col-md-9 top-in-single">
					<div class="col-md-5 single-top">	
						<ul id="etalage">
						    <li>
								<img class="etalage_thumb_image img-responsive" src="${root}/productImage?id=${customerProductSingle.productid}" alt="">
								<img class="etalage_source_image img-responsive" src="${root}/productImage?id=${customerProductSingle.productid}" alt="">
							</li>
						</ul>
					</div>	
					<div class="col-md-7 single-top-in">
						<div class="single-para">								
								<div class="para-grid">
									<span  class="add-to">${customerProductSingle.productprice}.000 VNĐ</span>
									<a href="${root}/customerProductCart/${customerProductSingle.productid}/${forward}" class="hvr-shutter-in-vertical cart-to">Thêm Giỏ Hàng</a>					
									<div class="clearfix"></div>
								 </div>
								 <h5>${customerProductSingle.category.categoryname}</h5>	
								 <p>${customerProductSingle.productdescription}</p>
																		
						</div>
					</div>
					<div class="clearfix"> </div>				
				</div>				
			<div class="clearfix"> </div>
		</div>
	</div>

src/main/webapp/WEB-INF/views/jsp/slidershow.jsp
<%@page contentType="text/html" pageEncoding="UTF-8"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<c:set var="root" value="${pageContext.request.contextPath}"/>
<div class="banner-mat">
		<div class="container">
			<div class="banner">

				<div class="slider">
					<ul class="rslides" id="slider1">
						<li><img src="${root}/images/banner-18.jpg" alt=""></li>
						<li><img src="${root}/images/banner-19.jpg" alt=""></li>
						<li><img src="${root}/images/banner-1546.png" alt=""></li>
						<li><img src="${root}/images/banner-ngoai-hang-anh-du-cup-c1-2018-19.png" alt=""></li>
					</ul>
				</div>
				<div class="banner-bottom">
					
				</div>
			</div>
		</div>
	</div>